name: test_workflow_dispatch_test

on: 
  workflow_dispatch:
    inputs:
      envs:
        description: 'List envs are deployed'     
        required: true
# on: 
#   push: 
#     branches: [test]
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Envs: test" 
